sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
env:
  global:
  - secure: pJN1apbK271/l87YzligwPzUH5/Rk31M32ubW0zM3l/sYwepRkvptbwKuh8BG6dpifwot/HbEZOktGyeDlgXqh4luUTnBDQOPaJeFQ9HNt+g6lxCuSJRh4K7WLvAYpJpHnj78r3BWEnRhmb4ie5CcfhA9H00+yErLnRv8Hp+7FaPnLl2IcFh505H5izDctimCc5OpHDmB6XEpURMeuMzYtjKHdKdJBghAsiKua1QdlCVLU6jPUybR2I4B+BlryP8tO24lpdic1iowNJ1AuvPaD0yvC495HSrRjuta+aBZ/HhMWW4xurFchYFOSx5nfHrIPGobChFVRDdW4jNwFAJ6sX3aJx6br3avgVuPZ3hG+Uqs4iSw7I0nP2CoMFCDKfJkhtgvcKS0pLUMwznGCfvOJlNqpHd3VrFqIqMBLj0vIUy7m6U5InmMtYqklhPvFL0WyVLX0p/o35a5v8kv+GVNPpZNNu8vrICkdefuzJ78JwoB7LZqUPdRLe8ZZhWIojY4d2xssSlJhdR2eEbtvHUfyVkp91jhXNFzYVUcd2DUXwaBGBFp/pBSJJ07uznNJOJXNDK4P6wd0DH0ULfJKGlQhUVEvCwJBqsRLlB1aMK/n17l0xIA1qkyRXMNVnIs6mB1dC1jLqiy4aV0jjLo5Qk7DPgCW8YBkE9s4RILi4g450=
before_install:
- >-
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ];
  then openssl aes-256-cbc -k "$password" -in id_rsa.enc -out deploy_key -d;
  fi
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- >-
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ];
  then wct --plugin sauce --skip-plugin local;
  fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- ./ghp.sh
