sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
env:
  global:
  - secure: p0/h1thEYPMwK1AR/XIv09h1Fb21PFl2orkAEwf5cMZmnAegdpys0ziQ/eI+2UQhhgyqxODHBRHBLUfmmv9KXjT0BLDLwxGCYXcGZT1htUhxh/Yp1pnyXRsqSgc5uu8FYEefsS1oApOyrHxCxq7HzNNeupoN28ZSbfpgyGq806GKgCp8d6z8DmCiy9ivgfjPTW8gxK8nEJnt8xFVCf2nzpYmjAwJ6KH3wKUNbrSEtSnOqoW11GKVUZBKDctXYA8sOuRmaMNq+v7K7l1bAfVqDIM9HMdY1MQjla9ARIKfbf53p7ArM6m2oZtl1in8AVdlFakIA6/ou7c7QEbFQEgs99Nt4k9KPNpxdnZ9IV675xx7lNsEIXUMb4DiQ1sR7i3+qN1iInNZQyJxU0Te/Bg+PvmuVtj/KtIlTpy8OPhAaYjxFqBE4FGFbR5wR/CsieNzzpQdrYEP0jLOiSdYb+/RonuNBK3Hhf32Mp02W2uEgUYCDtlIidMvMzONAeDS5vPg36Qs6atAJyvq/sKSxsX79rtJUghZhFngHj3OjTmdenL0UKY4rocxI12eMXG7LHimYRUSJczxcLJwULC4Mj5bhmlHSPbk8fx/eaAm6kpzLU1J8hzpfaR0ODxOUO4+kW8NYodaC/F+65Wn+lQQE0Z7FY3cY77Yto9sXmiBa6KkL0Y=
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password" in id_rsa.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- ./ghp.sh
